import { TypingDifficulty } from './typingtest.types';

const EASY_WORD_BANK = [
  'the', 'be', 'of', 'and', 'a', 'to', 'in', 'he', 'have', 'it', 'that', 'for', 'they', 'with', 'as', 'not',
  'on', 'she', 'at', 'by', 'this', 'we', 'you', 'do', 'but', 'his', 'from', 'they', 'say', 'her', 'she', 'or',
  'an', 'will', 'my', 'one', 'all', 'would', 'there', 'their', 'what', 'so', 'up', 'out', 'if', 'about', 'who',
  'get', 'which', 'go', 'me', 'when', 'make', 'can', 'like', 'time', 'no', 'just', 'him', 'know', 'take', 'people',
  'into', 'year', 'your', 'good', 'some', 'could', 'them', 'see', 'other', 'than', 'then', 'now', 'look', 'only',
  'come', 'its', 'over', 'think', 'also', 'back', 'after', 'use', 'two', 'how', 'our', 'work', 'first', 'well',
  'way', 'even', 'new', 'want', 'because', 'any', 'these', 'give', 'day', 'most', 'us', 'water', 'long', 'very',
  'great', 'small', 'every', 'found', 'still', 'between', 'name', 'should', 'home', 'big', 'give', 'air', 'line',
  'set', 'own', 'under', 'read', 'last', 'never', 'life', 'always', 'those', 'both', 'paper', 'together', 'got',
  'group', 'often', 'run', 'important', 'until', 'side', 'feet', 'car', 'mile', 'walk', 'white', 'sea', 'began',
  'grow', 'took', 'river', 'four', 'carry', 'state', 'once', 'book', 'hear', 'stop', 'without', 'second', 'late',
  'miss', 'idea', 'enough', 'eat', 'face', 'watch', 'far', 'real', 'almost', 'let', 'above', 'girl', 'sometimes',
  'mountain', 'cut', 'young', 'talk', 'soon', 'list', 'song', 'being', 'leave', 'family', 'body', 'music', 'color'
];

const MEDIUM_PARAGRAPHS = [
  'In the heart of the bustling city, morning light filtered through the tall glass buildings, casting long shadows across the crowded streets. People hurried along the sidewalks, coffee cups in hand, ready to begin another productive day. Technology has fundamentally reshaped how we communicate, work, and collaborate across vast distances. While modern tools provide remarkable convenience, the value of meaningful human connection and deep focus remains irreplaceable. Every great achievement begins with patience, steady discipline, and a willingness to learn from every setback encountered along the way.',
  'The ancient library stood at the edge of the village, its weathered stone walls covered in creeping ivy and moss. Inside, thousands of books lined the shelves from floor to ceiling, each one holding stories of distant lands and forgotten civilizations. Scholars traveled from across the country to study within its quiet halls, searching for wisdom in the pages of manuscripts written centuries ago. The librarian, an elderly woman with silver hair and kind eyes, knew the location of every volume and could recall passages from memory with remarkable precision.',
  'Cooking is one of the oldest and most universal forms of creative expression known to humanity. Every culture around the world has developed its own unique flavors, techniques, and traditions that reflect local ingredients and historical influences. From the delicate art of Japanese sushi preparation to the bold spices of Indian curries, food tells the story of a people and their connection to the land. Learning to cook well requires patience, practice, and a willingness to experiment with new combinations and unfamiliar methods.',
  'The migration patterns of birds have fascinated scientists and nature enthusiasts for centuries. Each year, millions of birds travel thousands of miles between their breeding grounds and winter habitats, navigating by the stars, the magnetic field of the earth, and landmarks they have memorized over generations. Some species, like the Arctic tern, make round trips of nearly fifty thousand miles, crossing entire continents and oceans in the process. Understanding these journeys helps researchers monitor environmental changes and protect critical stopover habitats.',
  'Music has the remarkable ability to transcend language barriers and connect people from entirely different backgrounds. A melody composed in one corner of the world can evoke powerful emotions in someone who has never visited that place or spoken that language. Throughout history, musicians have drawn inspiration from personal experiences, cultural traditions, and the natural world around them. Whether played on a grand piano in a concert hall or strummed on a guitar around a campfire, music remains one of the most profound forms of human communication.',
  'The development of modern transportation has dramatically changed the way people live, work, and interact with one another. Before the invention of the automobile, most people spent their entire lives within a few miles of where they were born. Trains, cars, and airplanes opened up new possibilities for travel, trade, and cultural exchange that were previously unimaginable. Today, high-speed rail networks and commercial aviation allow people to cross entire countries in just a few hours, making the world feel smaller and more connected than ever before.',
  'Volunteering in your local community can have a profound impact on both the people you help and your own personal growth. Whether you are serving meals at a shelter, tutoring children after school, or cleaning up a neighborhood park, the act of giving your time and energy to others creates meaningful bonds and strengthens social connections. Many volunteers report that helping others brings them a deep sense of purpose and fulfillment that is difficult to find elsewhere. Communities with active volunteer networks tend to be more resilient, inclusive, and supportive of all their members.',
  'The ocean covers more than seventy percent of the surface of the earth, yet we have explored less than five percent of its depths. Beneath the waves lies an extraordinary world of coral reefs, deep sea trenches, and underwater mountains that rival the tallest peaks on land. Marine biologists continue to discover new species every year, from bioluminescent jellyfish in the midnight zone to microscopic organisms that thrive near hydrothermal vents on the ocean floor. Protecting these fragile ecosystems is essential for maintaining the health of our entire planet.',
  'Photography has evolved from a complex chemical process requiring bulky equipment to an accessible art form that nearly everyone can practice with a smartphone in their pocket. Despite the simplicity of modern cameras, taking a truly compelling photograph still requires an understanding of composition, lighting, and timing. The best photographers learn to see the world differently, noticing patterns, contrasts, and moments of beauty that others might overlook. A single photograph can capture a feeling, tell a story, or preserve a memory that words alone cannot adequately describe.',
  'Regular physical exercise is one of the most effective ways to maintain both mental and physical health throughout your life. Even moderate activities like walking, swimming, or cycling for thirty minutes a day can reduce the risk of heart disease, improve mood, and increase overall energy levels. Exercise stimulates the release of endorphins, natural chemicals in the brain that promote feelings of happiness and reduce stress. Building a consistent fitness routine does not require an expensive gym membership or fancy equipment; it simply requires dedication and a commitment to moving your body every day.',
  'The history of chocolate stretches back thousands of years to the ancient civilizations of Central America, where the cacao bean was considered so valuable that it was used as currency. The Aztecs and Maya prepared a bitter, spicy drink from ground cacao beans mixed with water and chili peppers, which was reserved for royalty and special ceremonies. When Spanish explorers brought cacao back to Europe in the sixteenth century, sugar was added to create the sweet treat we know today. The journey from a sacred beverage to a beloved global confection is a fascinating tale of cultural exchange and culinary innovation.',
  'Space exploration represents one of the most ambitious and inspiring endeavors in human history. From the first satellite launched into orbit to the landing of rovers on the surface of Mars, each milestone has expanded our understanding of the cosmos and our place within it. The challenges of space travel are immense, requiring advances in propulsion, life support, and materials science that push the boundaries of what is technically possible. As private companies join national agencies in the race to explore beyond our planet, a new era of discovery and adventure is beginning to unfold.',
  'The art of storytelling has been central to human culture since the earliest days of civilization. Long before the invention of writing, people gathered around fires to share tales of heroic deeds, cautionary lessons, and explanations of the natural world. These oral traditions preserved the collective memory of communities and passed down essential knowledge from one generation to the next. Today, storytelling continues to thrive in countless forms, from novels and films to podcasts and video games, proving that the human desire to hear and tell stories is truly timeless.',
  'Climate change is one of the most pressing challenges facing the world today, affecting weather patterns, sea levels, and ecosystems on every continent. Scientists have documented rising global temperatures caused primarily by the burning of fossil fuels, deforestation, and industrial agriculture. The consequences of inaction include more frequent and severe natural disasters, food and water shortages, and the displacement of millions of people from their homes. Addressing this crisis will require unprecedented cooperation between governments, businesses, and individuals to reduce emissions and transition to sustainable energy sources.',
  'The game of chess has captivated minds for over fifteen hundred years, evolving from an ancient Indian strategy game into the globally recognized competition we know today. Each match is a battle of wits where players must think several moves ahead, anticipating their opponent while formulating their own plans of attack and defense. Grandmasters spend years studying opening sequences, middlegame tactics, and endgame techniques to sharpen their skills. Beyond competition, chess teaches valuable lessons about patience, critical thinking, and the importance of learning from mistakes.',
  'Architecture shapes the way we experience the spaces where we live, work, and gather. From the soaring arches of Gothic cathedrals to the clean lines of modern skyscrapers, buildings reflect the values, technologies, and artistic sensibilities of the societies that create them. Great architects balance aesthetic beauty with practical function, designing structures that are not only visually striking but also comfortable, accessible, and environmentally responsible. The best buildings stand as enduring monuments to human creativity, inspiring wonder and admiration for generations after their completion.',
  'Learning a second language opens doors to new cultures, career opportunities, and ways of thinking that would otherwise remain inaccessible. Research has shown that bilingual individuals often demonstrate greater cognitive flexibility, improved memory, and enhanced problem solving skills compared to monolingual speakers. The process of acquiring a new language can be challenging, requiring consistent practice, immersion in authentic materials, and a willingness to make mistakes along the way. However, the rewards of being able to communicate with people from different backgrounds and understand their perspectives are well worth the effort.',
  'The rainforests of the world are often called the lungs of the planet because of their critical role in producing oxygen and absorbing carbon dioxide from the atmosphere. These dense, tropical forests are home to an astonishing diversity of plant and animal species, many of which are found nowhere else on earth. Indigenous communities have lived in harmony with these forests for thousands of years, developing sophisticated knowledge of medicinal plants and sustainable farming practices. The rapid destruction of rainforests through logging, mining, and agricultural expansion threatens not only biodiversity but also the livelihoods of millions of people.',
  'The invention of the printing press by Johannes Gutenberg in the fifteenth century is widely regarded as one of the most transformative events in human history. Before its creation, books were painstakingly copied by hand, making them rare and expensive treasures accessible only to the wealthy and the clergy. The printing press made it possible to produce books quickly and affordably, democratizing access to knowledge and fueling the spread of new ideas across Europe. This revolution in communication laid the groundwork for the Renaissance, the Reformation, and the eventual rise of modern science and democratic governance.',
  'Sleep plays a vital role in maintaining overall health, yet millions of people around the world do not get the rest they need. During sleep, the body repairs tissues, consolidates memories, and regulates hormones that control growth and appetite. Chronic sleep deprivation has been linked to a wide range of health problems, including obesity, diabetes, cardiovascular disease, and weakened immune function. Establishing a consistent bedtime routine, limiting screen time before sleep, and creating a comfortable sleeping environment are simple but effective strategies for improving the quality and duration of your rest.',
  'Pottery is one of the oldest crafts in human history, with evidence of ceramic vessels dating back more than twenty thousand years. Early humans discovered that shaping wet clay and heating it in a fire created durable containers for storing food, water, and other essential supplies. Over time, potters developed increasingly sophisticated techniques, including the use of the wheel, glazes, and decorative patterns that transformed functional objects into works of art. Today, pottery remains a popular hobby and art form, connecting modern practitioners with a tradition that stretches back to the dawn of civilization.',
  'The science of nutrition has come a long way since the discovery of vitamins in the early twentieth century. Researchers now understand that the foods we eat have a profound impact on every aspect of our health, from energy levels and immune function to mood and cognitive performance. A balanced diet rich in fruits, vegetables, whole grains, and lean proteins provides the essential nutrients the body needs to function at its best. Despite the abundance of fad diets and conflicting advice, the fundamental principles of good nutrition remain remarkably simple: eat a variety of whole foods in appropriate portions and stay hydrated.',
  'Public libraries are among the most democratic institutions in modern society, offering free access to books, technology, and educational programs for people of all ages and backgrounds. Beyond lending books, libraries serve as community gathering spaces, homework help centers, and refuges for those seeking a quiet place to read, study, or simply escape the noise of daily life. Librarians are trained information professionals who can help patrons navigate an overwhelming sea of sources and find reliable answers to their questions. In an age of misinformation and digital overload, the value of a well-funded, well-staffed public library cannot be overstated.',
  'The sport of marathon running has grown from a niche athletic pursuit into a worldwide phenomenon that attracts millions of participants each year. Completing a marathon requires months of dedicated training, careful attention to nutrition, and the mental fortitude to push through exhaustion and discomfort over twenty-six point two miles. Runners of all ages and abilities line up at starting lines around the globe, from the iconic courses of Boston and London to small local races in rural communities. The sense of accomplishment that comes from crossing the finish line is a powerful reminder of what the human body and spirit can achieve with determination and perseverance.',
  'The Renaissance, which began in Italy during the fourteenth century and spread across Europe over the following two hundred years, was a period of extraordinary cultural, artistic, and intellectual achievement. Artists like Leonardo da Vinci, Michelangelo, and Raphael produced masterworks that continue to inspire admiration and study today. Scholars rediscovered the writings of ancient Greek and Roman thinkers, sparking a renewed interest in philosophy, literature, and the natural sciences. This remarkable flowering of creativity and learning transformed European society and laid the foundations for many of the ideas and institutions that shape our modern world.'
];

const HARD_PARAGRAPHS = [
  'The phenomenon of quantum entanglement fundamentally challenges our classical understanding of physical reality by introducing non-local, probabilistic outcomes at the subatomic level. While many researchers attempt to simplify these concepts for general consumption, the inherent complexity—often characterized by dense mathematical formalisms and abstract theoretical frameworks—remains a significant hurdle for those outside the discipline. Furthermore, the persistent debate regarding the interpretation of these mechanisms suggests that our current comprehension may be merely a precursor to a more profound, yet-to-be-discovered paradigm that bridges the gap between general relativity and quantum mechanics.',
  'Throughout the annals of jurisprudence, the tension between positivist and natural-law traditions has engendered innumerable philosophical controversies that remain unresolved to this day. Positivists—exemplified by scholars such as H.L.A. Hart and Hans Kelsen—maintain that the validity of law derives solely from its procedural enactment, irrespective of moral considerations; natural-law theorists, conversely, assert that unjust statutes lack genuine legal authority. This dichotomy, far from being a mere academic abstraction, has profound implications for constitutional interpretation, human-rights adjudication, and the legitimacy of international humanitarian interventions.',
  'The labyrinthine bureaucracies of multinational conglomerates often engender an organizational inertia that stifles innovation and obfuscates accountability. Executives, ensconced within hierarchical silos, may prioritize short-term quarterly earnings over the long-term strategic imperatives necessary for sustainable growth. Consequently, disruptive market entrants—unburdened by legacy infrastructure and byzantine approval processes—frequently outmaneuver their larger counterparts. Scholars of organizational behavior have long advocated for flatter, more agile corporate architectures; however, implementing such sweeping structural transformations requires navigating entrenched institutional resistance and overcoming deeply ingrained cultural predispositions.',
  'Epistemological inquiries into the nature and limits of human knowledge have preoccupied philosophers since antiquity, from Plato\'s allegory of the cave to Descartes\'s methodological skepticism. The fundamental question—"How can we distinguish justified, true belief from mere opinion?"—admits no universally satisfying answer, despite centuries of rigorous argumentation. Contemporary epistemologists grapple with challenges posed by Gettier counterexamples, the regress problem of justification, and the implications of cognitive psychology\'s demonstration that human reasoning is systematically susceptible to heuristic biases and logical fallacies that undermine our confidence in ostensibly rational deliberation.',
  'The geopolitical ramifications of climate change extend far beyond environmental degradation; they encompass resource scarcity, mass displacement, and the exacerbation of pre-existing socioeconomic inequalities across hemispheres. Small island developing states—already vulnerable to rising sea levels, intensified cyclonic activity, and coral-reef bleaching—face existential threats that demand immediate, coordinated international responses. Meanwhile, industrialized nations, whose cumulative greenhouse-gas emissions bear disproportionate responsibility for the crisis, must reconcile their economic imperatives with the moral obligation to finance adaptation and mitigation strategies in the most acutely affected regions of the Global South.',
  'Neuroplasticity, the brain\'s remarkable capacity to reorganize its synaptic connections in response to experience, injury, or environmental stimuli, has revolutionized our understanding of cognitive development and rehabilitation. Contrary to the long-held dogma that the adult brain is essentially fixed and immutable, longitudinal studies have demonstrated that targeted behavioral interventions—including mindfulness meditation, bilingual language acquisition, and intensive physical therapy—can induce measurable structural changes in cortical thickness, white-matter integrity, and functional connectivity. These findings carry profound implications for the treatment of neurodegenerative disorders, traumatic brain injuries, and age-related cognitive decline.',
  'The Peloponnesian War, meticulously chronicled by Thucydides in the fifth century BCE, remains an indispensable case study for scholars of international relations and military strategy. The protracted conflict between Athens and Sparta—spanning nearly three decades and culminating in the dissolution of Athenian hegemony—illustrates the dangers of imperial overreach, the fragility of democratic institutions under duress, and the catastrophic consequences of miscalculated alliances. Thucydides\'s unflinching analysis of political rhetoric, epidemiological devastation, and the moral corrosion wrought by prolonged warfare continues to resonate with contemporary observers of geopolitical conflict.',
  'In the realm of abstract mathematics, the Riemann Hypothesis—positing that all non-trivial zeros of the zeta function possess a real part equal to one-half—remains one of the most celebrated unsolved problems in number theory. Its resolution would have far-reaching consequences for our understanding of the distribution of prime numbers, cryptographic security protocols, and the deeper structural properties of the integers. Despite more than a century and a half of sustained effort by some of the finest mathematical minds, including Hilbert, Hardy, and Selberg, a definitive proof or disproof continues to elude the global research community.',
  'The philosophical doctrine of existentialism, as articulated by Jean-Paul Sartre, Simone de Beauvoir, and Albert Camus, posits that existence precedes essence—that human beings are "condemned to be free," bearing sole responsibility for constructing meaning in an inherently indifferent universe. This radical assertion of individual autonomy, while intellectually liberating, imposes a considerable psychological burden; the absence of predetermined purpose engenders existential anxiety, or what Kierkegaard termed "the dizziness of freedom." Nevertheless, existentialist thought has profoundly influenced twentieth-century literature, psychotherapy, and political philosophy, providing a framework for understanding authenticity, commitment, and moral responsibility.',
  'The intricacies of macroeconomic policy during periods of stagflation—characterized by the simultaneous occurrence of stagnant economic growth, elevated unemployment, and persistent inflationary pressures—present policymakers with an exceptionally challenging trilemma. Conventional Keynesian prescriptions for stimulating aggregate demand risk exacerbating inflation, while monetarist approaches emphasizing restrictive credit policies may deepen recessionary conditions and disproportionately burden working-class households. The experience of the nineteen-seventies, when oil-price shocks and supply-side disruptions confounded prevailing economic orthodoxies, underscores the limitations of any single theoretical framework in addressing the multifaceted complexities of real-world economies.',
  'Paleontological evidence, meticulously assembled from fossilized remains, isotopic analyses, and sedimentary stratigraphy, has revealed that the Cretaceous-Paleogene extinction event—approximately sixty-six million years ago—was precipitated by the catastrophic impact of a massive asteroid near what is now the Yucatan Peninsula of Mexico. The resultant firestorms, seismic upheavals, and prolonged "impact winter" obliterated approximately seventy-five percent of all terrestrial and marine species, including the non-avian dinosaurs. This cataclysmic episode, while devastating, ultimately created the ecological niches that facilitated the adaptive radiation of mammals and the eventual emergence of primates.',
  'The art of rhetoric, as codified by Aristotle in his treatise on persuasion, encompasses three principal modes of appeal: ethos, the credibility and moral character of the speaker; pathos, the emotional resonance elicited in the audience; and logos, the logical coherence and evidentiary rigor of the argument itself. Mastery of these interrelated dimensions requires not merely linguistic dexterity but also a sophisticated understanding of audience psychology, cultural context, and the subtle interplay between rational deliberation and affective persuasion. In democratic societies, where public discourse shapes policy and governance, the cultivation of rhetorical competence remains an indispensable civic virtue.',
  'The Baroque period in European music, spanning roughly from sixteen hundred to seventeen fifty, witnessed an unprecedented efflorescence of compositional innovation and virtuosic performance. Composers such as Johann Sebastian Bach, George Frideric Handel, and Antonio Vivaldi developed intricate contrapuntal techniques, elaborate ornamentation, and dramatic contrasts between loud and soft dynamics that defined the era\'s distinctive aesthetic. The invention of new instruments—including the fortepiano and the modern violin family—expanded the timbral palette available to composers, while the establishment of public opera houses and concert venues democratized access to musical performance beyond the exclusive patronage of aristocratic courts.',
  'Anthropological fieldwork among indigenous Amazonian communities has illuminated the extraordinary depth and sophistication of traditional ecological knowledge systems that have sustained these populations for millennia. Ethnobotanical surveys reveal that certain tribes can identify and utilize over fifteen hundred distinct plant species for medicinal, nutritional, and ritualistic purposes—a pharmacological repertoire that far surpasses the catalogued knowledge of most contemporary Western herbalists. The accelerating encroachment of deforestation, extractive industries, and acculturation pressures threatens the irreversible erosion of these invaluable knowledge traditions, along with the linguistic diversity through which they are transmitted.',
  'The architectural philosophy of Frank Lloyd Wright, encapsulated in his concept of "organic architecture," sought to dissolve the conventional boundaries between built environments and the natural landscapes they inhabit. Wright\'s masterworks—including Fallingwater, the Guggenheim Museum, and Taliesin West—demonstrate a remarkable synthesis of structural audacity, material sensitivity, and spatial fluidity that continues to influence contemporary architectural practice. His insistence that buildings should grow naturally from their sites, employing indigenous materials and responding to topographical contours, anticipated many of the sustainability principles that have become central to twenty-first-century design discourse.',
  'The historiographical debate surrounding the decline and fall of the Roman Empire has generated a voluminous and contentious body of scholarship spanning more than five centuries. Edward Gibbon\'s magisterial narrative attributed the collapse to moral decadence, military overextension, and the enervating influence of Christianity; subsequent historians have proposed alternative explanations emphasizing fiscal insolvency, demographic pressures, environmental degradation, and the cumulative impact of barbarian migrations. Contemporary scholars increasingly reject monocausal explanations, arguing instead that the disintegration of Roman political authority was a multidimensional process involving the complex interplay of internal vulnerabilities and external pressures over several centuries.',
  'Psycholinguistic research into the mechanisms of bilingual language processing has revealed that the two linguistic systems of a bilingual individual are not discretely compartmentalized but rather continuously co-activated, even when only one language is ostensibly in use. This parallel activation necessitates sophisticated executive-control mechanisms—particularly inhibitory processes mediated by the prefrontal cortex—to manage cross-linguistic interference and ensure contextually appropriate language production. The cognitive demands of this perpetual linguistic juggling act may, paradoxically, confer neuroprotective benefits, as longitudinal studies suggest that lifelong bilingualism is associated with a delayed onset of dementia symptoms by approximately four to five years.',
  'The ethical dilemmas posed by advances in genetic engineering—particularly the development of clustered regularly interspaced short palindromic repeats technology for germline editing—have ignited fierce interdisciplinary debates among bioethicists, geneticists, legal scholars, and theologians. Proponents argue that heritable genetic modifications could eradicate devastating hereditary diseases such as sickle-cell anemia, Huntington\'s chorea, and cystic fibrosis; critics counter that the unpredictable off-target effects, the specter of eugenic applications, and the irreversible alteration of the human gene pool raise moral concerns of unprecedented magnitude that demand the most stringent precautionary oversight.',
  'The transition from feudal agrarianism to industrial capitalism in eighteenth- and nineteenth-century Europe precipitated sweeping transformations in social stratification, labor relations, and demographic patterns that fundamentally reconfigured the fabric of Western civilization. The mechanization of textile production, the harnessing of steam power, and the expansion of railway networks catalyzed unprecedented urbanization, drawing millions of rural laborers into burgeoning factory towns characterized by squalid living conditions, exploitative wages, and the systematic erosion of traditional communal bonds. These convulsive socioeconomic dislocations engendered new forms of political consciousness, culminating in the emergence of organized labor movements, socialist ideologies, and eventually the welfare state.',
  'The biodiversity crisis currently unfolding across the planet represents what many ecologists describe as the sixth mass extinction event in the geological history of life on Earth. Species are disappearing at rates estimated to be one hundred to one thousand times greater than the natural background extinction rate, driven primarily by habitat destruction, overexploitation, invasive species proliferation, pollution, and anthropogenic climate disruption. The cascading ecological consequences of this unprecedented biodiversity loss—including the collapse of pollination networks, the destabilization of food webs, and the diminished resilience of ecosystems to environmental perturbations—threaten the very foundations of human food security, public health, and economic prosperity.',
  'The phenomenology of aesthetic experience, as theorized by philosophers from Immanuel Kant to Maurice Merleau-Ponty, resists reduction to purely cognitive or affective categories, occupying instead a liminal space between subjective perception and intersubjective communicability. Kant\'s notion of "disinterested pleasure"—the idea that genuine aesthetic judgment transcends personal utility and sensory gratification—remains foundational, yet subsequent thinkers have complicated this framework by emphasizing the embodied, culturally situated, and historically contingent dimensions of artistic appreciation. The irreducible plurality of aesthetic responses to a single work of art underscores the profound complexity of human consciousness and its capacity for meaning-making.',
  'Maritime archaeology, the systematic study of submerged cultural heritage sites, has undergone a methodological revolution with the advent of remotely operated vehicles, side-scan sonar technology, and photogrammetric three-dimensional modeling. These technological innovations have enabled researchers to survey and document shipwrecks, submerged settlements, and underwater landscapes at depths previously inaccessible to human divers, yielding unprecedented insights into ancient trade networks, naval warfare, and coastal settlement patterns. The preservation conditions in anaerobic marine sediments often surpass those of terrestrial sites, producing remarkably intact organic artifacts—including textiles, wooden implements, and botanical remains—that illuminate aspects of past societies rarely captured in the documentary record.',
  'The philosophy of language, as developed by Ludwig Wittgenstein in his later work, fundamentally challenged the representationalist assumption that words derive their meaning from corresponding to discrete objects or states of affairs in the external world. Wittgenstein\'s concept of "language games" emphasized that linguistic meaning is constituted through use within specific social practices and forms of life, rather than through abstract referential relationships. This pragmatic turn had far-reaching implications for epistemology, philosophy of mind, and the social sciences, suggesting that many traditional philosophical problems arise not from genuine metaphysical puzzles but from conceptual confusions engendered by the misleading surface grammar of natural language.',
  'The development of penicillin, from Alexander Fleming\'s serendipitous observation of bacterial inhibition by a contaminating mold in nineteen twenty-eight to the industrial-scale production that saved countless lives during the Second World War, exemplifies the often circuitous and collaborative nature of transformative scientific breakthroughs. Fleming\'s initial discovery languished in relative obscurity for over a decade until Howard Florey and Ernst Boris Chain, working at Oxford University, undertook the painstaking biochemical purification and clinical trials that demonstrated the antibiotic\'s extraordinary therapeutic efficacy. This landmark achievement inaugurated the antibiotic era in medicine; however, the subsequent emergence of multi-drug-resistant bacterial strains now threatens to undo these gains, confronting humanity with the sobering prospect of a post-antibiotic future.',
  'Comparative mythology, the scholarly discipline that examines structural parallels and thematic correspondences across the mythological traditions of disparate cultures, has revealed striking recurrences—including flood narratives, cosmogonic creation accounts, and heroic quest motifs—that transcend geographical, linguistic, and temporal boundaries. Joseph Campbell\'s monomyth theory, articulated in his influential work "The Hero with a Thousand Faces," posits that these cross-cultural similarities reflect universal archetypes embedded within the collective unconscious of the human species. Critics, however, have cautioned against the reductive tendencies of such universalizing frameworks, arguing that the specificities of cultural context, historical circumstance, and indigenous interpretation must be accorded primacy in any responsible hermeneutical analysis of mythological material.'
];

export const generateTypingPrompt = (difficulty: TypingDifficulty): string => {
  if (difficulty === 'easy') {
    const shuffled = [...EASY_WORD_BANK].sort(() => Math.random() - 0.5);
    const selected = [];
    while (selected.length < 130) {
      selected.push(...shuffled.slice(0, Math.min(shuffled.length, 130 - selected.length)));
    }
    return selected.slice(0, 130).join(' ');
  }

  if (difficulty === 'medium') {
    const chosen = MEDIUM_PARAGRAPHS[Math.floor(Math.random() * MEDIUM_PARAGRAPHS.length)];
    return chosen;
  }

  const chosen = HARD_PARAGRAPHS[Math.floor(Math.random() * HARD_PARAGRAPHS.length)];
  return chosen;
};